### DISCUSSION TITLE
v1.1.0

### DISCUSSION THREAD

**Discussion by rytswd** [upsidr/merge-gatekeeper#33] [Announcements]
## Minor Release

v1.1.0 includes a new feature of adding "ignored" list of jobs 🎉

The configuration will look something like below:

```yaml
---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@main
        with:
          ignored: failing-test1,failing-test2,another-experimental-job
          token: ${{ secrets.GITHUB_TOKEN }}
```

You can specify the list of items by comma-separated string.

---

### 🎁 Features

- Add an argument to ignore jobs #30 (fixes #17)

### 🐞 Bug Fixes

None

(There was one ticket (#31) related to #30.)
 
### 🔬 Misc

None

---

## Other Note

We have faced a significant disruption due to a small typo in Merge Gatekeeper code base, which caused all of our internal CI setup to fail and block us from merging PRs. This was related to the release, but also how we used `main` as the version reference.
If this has caused any disruption to your workflow, we are extremely sorry for not catching this earlier, and will aim to provide better control for future changes.

As preventative measures, we will be updating some of the documentation to note how you should be using `v1` tag (or more specific version such as `v1.1`, `v1.0.2`, etc.). Those will be updated after we do extra testing internally and ensure the stability of the latest code base. Also, we will work to add more strict test cases and close reviews to catch any unwanted behaviours.

<hr /><em>This discussion was created from the release <a href='https://github.com/upsidr/merge-gatekeeper/releases/tag/v1.1.0'>v1.1.0</a>.</em>
