### ISSUE TITLE
Gatekeeper misses failures in matrix jobs

### ISSUE THREAD

**Issue by allanlewis** [upsidr/merge-gatekeeper#27]
I have a [matrix job][1] that tests a component in two configurations. When one fails, Merge Gatekeeper passes - the logs don't show my matrix jobs in the list reported for each status.

My matrix job is a Python library and is configured something like this:

```yaml
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        tox-env: [env1, env2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: tox -e ${{ matrix.tox-env }}
```

[1]: https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
