### ISSUE TITLE
Support spaces and newlines in ignored jobs

### ISSUE THREAD

**Issue by rytswd** [upsidr/merge-gatekeeper#46]
Original request from #43

> Similar to https://github.com/upsidr/merge-gatekeeper/pull/39, this PR removes trailling and leading whitespace from ignored job. It also adds support for using newlines in the ignored jobs. This should allow users to use merge gatekeeper in the following way:

```yaml
jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored: |
            my_job1,
            my_job2,
            my_job3
```

--

We have merged a partial fix with #39, which adds this support to some extent. But there should be a better handling including providing more details as to which jobs are ignored.
