### ISSUE TITLE
Update docs to enumerate the specific permissions needed by merge-gatekeeper

### ISSUE THREAD

**Issue by jdechicchis** [upsidr/merge-gatekeeper#62]
Thank you for making this Action, super helpful! When deploying this action, I noticed that restricting the permissions to the following seemed sufficient:

```yaml
name: merge-gatekeeper
on:
  pull_request:
    branches:
    - main

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions: # Restrict permissions. See https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      checks: read
      statuses: read
    steps:
    - name: Run Merge Gatekeeper
      uses: upsidr/merge-gatekeeper@v1.2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```

I think it would be helpful to update the docs with these permissions if they look correct. Happy to make a PR with these docs changes!
