### ISSUE TITLE
Hitting Docker rate limit and ways to avoid that

### ISSUE THREAD

**Issue by Axelcouty** [upsidr/merge-gatekeeper#69]
Hello !

First thanks for this project :).

I'm working with merge-gatekeeper as a github action like this:
```
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

It seems that for our projects every Pull Requests triggers this action which always build a docker image using this [Dockerfile](https://github.com/upsidr/merge-gatekeeper/blob/main/Dockerfile).
The FROM uses a [default docker repository](https://github.com/upsidr/merge-gatekeeper/blob/main/Dockerfile#L3) which is prone to rate limits.

To my knowledge there is currently no way to avoid the issue, here are random thoughts:
- Allow to override the base repository
- Use [amazon ECR repository](https://gallery.ecr.aws/docker/library/golang)
- Something else ?

What do you think ?
