### ISSUE TITLE
Jobs are deducted on consecutive runs

### ISSUE THREAD

**Issue by leeran88** [upsidr/merge-gatekeeper#78]
Hi team!

We've been using merge-gatekeeper in our team for a while and enjoying it 🙂 

Recently I've noticed that when I run the merge gatekeeper for the first time on a PR, I get the complete list of Jobs, but on future run on the same branch/PR, I get only a small portion of them (maybe only the first ones in the workflow..). Important to say that all jobs actions are running on the CI when this issue is happening.

I did a test, pushed a commit on a file, that cause some Jobs to trigger. Then pushed another commit on the same file, cause the exact same Jobs to run. But there was a difference in the jobs on Merge gatekeeper.

For example, a log for the first run:
```
Start processing validator: merge-gatekeeper....
3 out of 3

Total job count:       3
Completed job count:   3
Incompleted job count: 0
Failed job count:      0
Ignored job count:     1
```

Log for a consecutive run: (similar commit on the same place)
```
Start processing validator: merge-gatekeeper....
15 out of 15

Total job count:       15
Completed job count:   15
Incompleted job count: 0
Failed job count:      0
Ignored job count:     1
```

This is my `merge-gatekeeper.yml`:
```
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@main
        with:
          token: ***
          ignored: Upload Artifacts
```

Is this a bug?
Would appreciate your help, thanks! 🙏 ❤️
