### ISSUE TITLE
Merge Gatekeeper succeeds before all status checks are completed

### ISSUE THREAD

**Issue by smokhasi** [upsidr/merge-gatekeeper#84]
We use Merge Gatekeeper across all our projects and have found it to be an excellent tool for overcoming some limitations of GitHub Actions.

Recently, we added Playwright end-to-end integration tests as status checks in our internal application repository. These tests are triggered only after the build, lint, and unit test checks, which take approximately 10 minutes to complete.

However, since the Playwright check is not part of the initial set of checks that run when a PR is opened, we are encountering an issue where Merge Gatekeeper marks the PR as successful before the Playwright tests have even started.

**Expected Behavior**
We would like Merge Gatekeeper to consider the Playwright tests before allowing a PR to be merged.

**Questions:**

- Is there a way to specify certain jobs as required when Merge Gatekeeper is triggered, particularly for specific file paths?
- Alternatively, can Merge Gatekeeper periodically re-check the list of jobs after initially succeeding to ensure that all relevant checks have completed?

Would appreciate any guidance on how to configure this behavior. Thanks!

**Comment by smokhasi** [comment]
Overcame this limitation by using [`myrotvorets/set-commit-status-action`](https://github.com/myrotvorets/set-commit-status-action). Spoofed the context and commit_sha, and set the status to `pending` until the playwright check starts
```
    steps:
      - uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: pending
          description: 'Tests are yet to run...'
          context: 'your context here'
```
